language: python
python:
     - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
     - PLATFORMIO_CI_SRC=src

install:
    - pip install -U platformio

    - wget https://github.com/marvinroger/homie-esp8266/archive/develop.zip -O /tmp/homie2.zip
    - unzip /tmp/homie2.zip -d /tmp

    - platformio lib -g install "ArduinoJson" "AsyncMqttClient" "Bounce2" "Adafruit Unified Sensor" "Adafruit BMP085 Unified" "rc-switch"

script:
    - platformio ci --lib="/tmp/homie-esp8266-develop" --board=d1_mini --board=nodemcuv2
